### ISSUE TITLE
Trying to mount an ISO instantly crashes on unrooted Nexus 5X

### ISSUE THREAD

**Issue by C0rn3j** [Streetwalrus/android_usb_msd#9]
Latest Android update, tried antergos-17.7-x86_64 and Win8.1_English_x64, both crash the moment I press mount.

Using the 0.4 usbmountr version from fdroid.

EDIT: Apparently this app needs root, the Nexus 5X I used wasn't rooted.

Would it be possible to fix it so that it says "root required" instead of crashing?

**Comment by Streetwalrus** [comment]
I can reproduce. I'm already handling failure to obtain root access, but maybe it only works on rooted devices when you reject it.

I'm away till next week so it'll take some time before I check it out.

**Comment by C0rn3j** [comment]
>but maybe it only works on rooted devices when you reject it.

Denying root access doesn't crash on my other rooted phone, so this seems to be the case.

**Comment by Streetwalrus** [comment]
Oddly enough, I can't reproduce this anymore. Can you get me a logcat of the crash?

**Comment by C0rn3j** [comment]
```
07-27 18:13:53.365  3734  4038 D audio_hw_primary: enable_snd_device: snd_device(78: vi-feedback)
07-27 18:13:53.365  3734  4038 D audio_hw_primary: enable_audio_route: usecase(21) apply and update mixer path: spkr-vi-record
07-27 18:13:53.372 15050 15083 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
07-27 18:13:53.372 15050 15083 E AndroidRuntime: Process: streetwalrus.usbmountr, PID: 15050
07-27 18:13:53.372 15050 15083 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at streetwalrus.usbmountr.MainActivity$UsbScript.doInBackground(MainActivity.kt:92)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at streetwalrus.usbmountr.MainActivity$UsbScript.doInBackground(MainActivity.kt:67)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-27 18:13:53.372 15050 15083 E AndroidRuntime: 	... 4 more
07-27 18:13:53.375  4868 19147 W ActivityManager:   Force finishing activity streetwalrus.usbmountr/.MainActivity
07-27 18:13:53.394  3734  4038 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
07-27 18:13:53.456  4868 10307 I OpenGLRenderer: Initialized EGL, version 1.4
07-27 18:13:53.456  4868 10307 D OpenGLRenderer: Swap behavior 1
07-27 18:13:53.463 11566 11597 I Adreno  : QUALCOMM build                   : 6818200, Idb2b4cb785
07-27 18:13:53.463 11566 11597 I Adreno  : Build Date                       : 11/18/16
07-27 18:13:53.463 11566 11597 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
07-27 18:13:53.463 11566 11597 I Adreno  : Local Branch                     : N25
07-27 18:13:53.463 11566 11597 I Adreno  : Remote Branch                    : 
07-27 18:13:53.463 11566 11597 I Adreno  : Remote Branch                    : 
07-27 18:13:53.463 11566 11597 I Adreno  : Reconstruct Branch               : 
07-27 18:13:53.476 11566 11597 I OpenGLRenderer: Initialized EGL, version 1.4
07-27 18:13:53.476 11566 11597 D OpenGLRenderer: Swap behavior 1
07-27 18:13:53.529  4868  4877 I art     : Background partial concurrent mark sweep GC freed 17760(1137KB) AllocSpace objects, 6(164KB) LOS objects, 33% free, 23MB/35MB, paused 1.340ms total 112.305ms
07-27 18:13:53.556 15050 15069 D OpenGLRenderer: endAllActiveAnimators on 0x7e434d1400 (RippleDrawable) with handle 0x7e361685c0
07-27 18:13:53.928  3734  4038 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback
07-27 18:13:53.943  3734  4038 D audio_hw_primary: disable_snd_device: snd_device(78: vi-feedback)
07-27 18:13:53.944  3734  4038 D audio_hw_primary: disable_audio_route: usecase(21) reset and update mixer path: spkr-vi-record
07-27 18:13:54.038  4868 15751 I ActivityManager: Process com.google.android.apps.docs.editors.slides (pid 14896) has died
07-27 18:13:54.039  4868 15751 D ActivityManager: cleanUpApplicationRecord -- 14896
```

**Comment by Streetwalrus** [comment]
I'm not really sure what's going on here but it might be related to https://github.com/Chainfire/libsuperuser/commit/226d21bb5b68073f483f2c151208ee1e95ad8aae. I'm going to handle the NPE anyway and that should do the trick.

**Comment by C0rn3j** [comment]
I don't experience the crash on 0.5 anymore.

Thanks!

**Comment by Streetwalrus** [comment]
Great! Thanks for the report.
